
server:
  port: 9001
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: "jdbc:mysql://207.180.226.46:3306/tapcard_test?useSSL=false&serverTimezone=Africa/Harare&allowPublicKeyRetrieval=true"
    username: developer
    password: ch@ng3itDev
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true