server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/terminal_devices?useSSL=false
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

